[[session]]
name = "git config"
path = "~/.gitconfig"
startup_command = "nvim .gitconfig"
preview_command = "bat --color=always ~/.gitconfig"

[[session]]
name = "zshrc config"
path = "~/.zshrc"
startup_command = "nvim .zshrc"
preview_command = "bat --color=always ~/.zshrc"

[[session]]
name = "Projects"
path = "~/Documents/PlatformIO/Projects"
startup_command = "ls"
preview_command = "eza --tree --level=2 --color=always ~/Documents/PlatformIO/Projects"

[[session]]
name = "herdr config"
path = "~/.config/herdr"
startup_command = "nvim config.toml"
preview_command = "bat --color=always config.toml"

[[session]]
name = "sesh"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always sesh.toml"

[[session]]
name = "nvim plugins"
path = "~/.config/nvim/lua/plugins"
startup_command = "yazi"

[[session]]
name = "kitty"
path = "~/.config/kitty/"
startup_command = "nvim kitty.conf"
preview_command = "bat --color=always ~/.kitty.conf"

[[session]]
name = "nvim config"
path = "~/.config/nvim/lua/config"
startup_command = "yazi"


[[session]]
name = "hyprland"
path = "~/.config/hypr/"
startup_command = "yazi"

[[session]]
name = "htl pos"
path = "~/workspace/htl/POS/"
startup_command = "yazi"

[[session]]
name = "htl syp"
path = "~/workspace/htl/POS/"
startup_command = "yazi"

[[session]]
name = "akaryon"
path = "~/workspace/akaryon-development.com/gitlab/"
startup_command = "yazi"

[[session]]
name = "Github"
path = "~/workspace/github.com/tombra2/"
startup_command = "yazi"

[[session]]
name = "Probe"
path = "~/workspace/probe/"
startup_command = "yazi"


