[colors]
[colors.primary]
background = "#121212"
foreground = "#ffffff"

[colors.normal]
black   = "#121212"
red     = "#c26252"
green   = "#d0642b"
yellow  = "#cd5d34"
blue    = "#7675d2"
magenta = "#c25bc3"
cyan    = "#7775d2"
white   = "#ffffff"

[colors.bright]
black   = "#9e9e9e"
red     = "#f1836e"
green   = "#e27941"
yellow  = "#fd7e48"
blue    = "#9b95ff"
magenta = "#f176f9"
cyan    = "#9c95ff"
white   = "#ffffff"

[colors.cursor]
text   = "#121212"
cursor = "#ffffff"
