# Background and foreground colors
background = #121212
foreground = #ffffff

# Standard colors
palette = 0=#121212
palette = 1=#fc3023
palette = 2=#b96564
palette = 3=#fc3023
palette = 4=#6479d2
palette = 5=#af5ed8
palette = 6=#6a76cc
palette = 7=#ffffff

# Bright colors
palette = 8=#9e9e9e
palette = 9=#ff523d
palette = 10=#e78684
palette = 11=#ff523d
palette = 12=#879aff
palette = 13=#dc79ff
palette = 14=#8d96ff
palette = 15=#ffffff
