$color = rgba(18, 18, 18, 1)
$inner_color = rgba(18, 18, 18, 0.66)
$outer_color = rgba(175, 94, 216, 1)
$font_color = rgba(255, 255, 255, 1)
$placeholder_color = rgba(255, 255, 255, 0.7)
$check_color = rgba(106, 118, 204, 1)
