vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "U", ":UndotreeToggle | wincmd h<CR>", { desc = "Toggle Undotree and move left" })
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "u", "uzz")
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set({ "n", "v", "i" }, "<C-q>", "<cmd>wa | qa<cr>", { desc = "Save all and quit" })
vim.keymap.set("i", "<C-s>", "<Esc><cmd>w<cr>", { desc = "Save and exit insert mode" })
vim.keymap.set("n", "<C-s>", "<cmd>w<cr>", { desc = "Save file" })
vim.keymap.set("i", "jj", "<Esc>", { desc = "Escape" })
vim.keymap.set("i", "kk", "<Esc>", { desc = "Escape" })
vim.keymap.set("i", "hh", "<Esc>", { desc = "Escape" })
vim.keymap.set("i", "lll", "<Esc>", { desc = "Escape" })
vim.keymap.set("n", "<left>", '<cmd>echo "Use h to move!!"<CR>')
vim.keymap.set("n", "<right>", '<cmd>echo "Use l to move!!"<CR>')
vim.keymap.set("n", "<up>", '<cmd>echo "Use k to move!!"<CR>')
vim.keymap.set("n", "<down>", '<cmd>echo "Use j to move!!"<CR>')

vim.keymap.set("n", "<leader><leader>", function()
  require("fzf-lua").buffers()
end, { desc = "FZF Buffers", remap = false })

vim.keymap.set("n", "<C-b>", "<cmd>Oil --float<CR>", { desc = "Open Parent Directory in Oil" })
vim.keymap.set("n", "<C-a>", "ggVG")

vim.keymap.set("n", "<leader>ab", ":!pio run<CR>", { silent = true })
vim.keymap.set("n", "<leader>ah", ":!pio home<CR>", { silent = true })
vim.keymap.set("n", "<leader>au", ":!pio run --target upload<CR>", { silent = true })
