# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

unbind = SUPER ,W
unbind = SUPER, TAB
unbind = SUPER, P
unbind = SUPER, C

unbind = , PRINT
unbind = SHIFT, PRINT
unbind = ALT, PRINT
unbind = SUPER, PRINT

bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER , E, File manager, exec, omarchy-launch-tui yazi
bindd = SUPER , B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password


bind = SUPER, W, exec, uwsm-app -- webapp-launcher "Word"
bind = SUPER, Tab, workspace, previous
bind = SUPER, Q, killactive
bindd = SUPER, P, Screenshot with editing, exec, omarchy-cmd-screenshot
bindd = SUPER, C, Color picker, exec, pkill hyprpicker || hyprpicker -a

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER , A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
#
 bind = CTRL, left, movefocus, l
 bind = CTRL, right, movefocus, r
 bind = CTRL, up, movefocus, u
 bind = CTRL, down, movefocus, d
# # Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
