set -l background 1e2227
set -l foreground abb2bf
set -l selection 61afef
set -l comment 495162
set -l red e05561
set -l orange d19a66
set -l yellow d18f52
set -l green 8cc265
set -l purple c162de
set -l sky 61afef
set -l pink c678dd

set -g fish_color_normal $foreground
set -g fish_color_command $sky
set -g fish_color_keyword $pink
set -g fish_color_quote $yellow
set -g fish_color_redirection $foreground
set -g fish_color_end $orange
set -g fish_color_error $red
set -g fish_color_param $purple
set -g fish_color_comment $comment
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator $green
set -g fish_color_escape $pink
set -g fish_color_autosuggestion $comment

set -g fish_pager_color_progress $comment
set -g fish_pager_color_prefix $sky
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $comment
set -g fish_pager_color_selected_background --background=$selection
