include=~/.local/share/omarchy/default/mako/core.ini

# One Dark Pro Darker
text-color=#e6e6e6
border-color=#61afef
background-color=#1e2227cc
progress-color=source #43495699
width=420
height=110
padding=9,14
border-size=1
border-radius=0
font=Liberation Sans 11
anchor=top-right
outer-margin=10
margin=8
default-timeout=5000
max-icon-size=32
layer=overlay

[urgency=low]
default-timeout=3000
border-color=#495162
border-size=1
text-color=#d7dae0
background-color=#1e2227b3

[urgency=critical]
default-timeout=0
border-color=#e05561
border-size=1
text-color=#e6e6e6
background-color=#1e2227d9
layer=overlay

[app-name=Spotify]
invisible=1

[mode=do-not-disturb]
invisible=true

[mode=do-not-disturb app-name=notify-send]
invisible=false
