accent = "#569CD6"
cursor = "#D4D4D4"
foreground = "#D4D4D4"
background = "#1F1F1F"
selection_foreground = "#ffffff"
selection_background = "#264F78"

color0 = "#1F1F1F"
color1 = "#F44747"
color2 = "#6A9955"
color3 = "#DCDCAA"
color4 = "#569CD6"
color5 = "#C586C0"
color6 = "#56B6C2"
color7 = "#D4D4D4"
color8 = "#808080"
color9 = "#F44747"
color10 = "#6A9955"
color11 = "#DCDCAA"
color12 = "#569CD6"
color13 = "#C586C0"
color14 = "#56B6C2"
color15 = "#D4D4D4"
