onboarding = false

[theme]
name = "one-dark"

auto_switch = false
[terminal]
default_shell = "/usr/bin/bash"
shell_mode = "non_login"
new_cwd = "follow"

[keys]
prefix = "ctrl+space"
help = "prefix+?"
detach = "prefix+d"
reload_config = "prefix+q"
new_workspace = "alt+shift+n"
rename_workspace = "prefix+shift+r"
close_workspace = "prefix+shift+x"
workspace_picker = "prefix+w"
goto = "prefix+g"
previous_workspace = ["prefix+shift+p", "alt+k"]
next_workspace = ["prefix+shift+n", "alt+j"]
new_tab = "alt+n"
rename_tab = "prefix+r"
previous_tab = ["prefix+p", "alt+h"]
next_tab = ["prefix+n", "alt+l"]
switch_tab = ["prefix+1..9", "alt+1..9"]
close_tab = "prefix+k"
focus_pane_left = "ctrl+alt+left"
focus_pane_down = "ctrl+alt+down"
focus_pane_up = "ctrl+alt+up"
focus_pane_right = "ctrl+alt+right"
split_vertical = ["prefix+v", "alt+shift+enter"]
split_horizontal = ["prefix+h", "alt+enter"]
close_pane = ["prefix+x", "alt+esc"]
copy_mode = "prefix+["
zoom = "prefix+z"
resize_mode = "prefix+shift+z"

[[keys.command]]
key = "ctrl+f"
type = "popup"
command = '"$HOME/.config/script/herdr-sessionizer"'
description = "open project sessionizer"
width = "80%"
height = "80%"

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "willfish.herdr-navigator.left"
description = "navigate left (Neovim/Herdr)"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "willfish.herdr-navigator.down"
description = "navigate down (Neovim/Herdr)"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "willfish.herdr-navigator.up"
description = "navigate up (Neovim/Herdr)"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "willfish.herdr-navigator.right"
description = "navigate right (Neovim/Herdr)"

[ui]
mouse_capture = true
copy_on_select = true
pane_borders = true
pane_gaps = false
show_agent_labels_on_pane_borders = true
hide_tab_bar_when_single_tab = false
prompt_new_tab_name = false
agent_panel_sort = "priority"
accent = "blue"

[ui.toast]
delivery = "system"
delay_seconds = 1

[ui.sound]
enabled = true

[session]
resume_agents_on_restore = true

[experimental]
pane_history = false

[advanced]
scrollback_limit_bytes = 50000000
